version: '3'
services:
  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: p@ssword
      MYSQL_USER: testUser
      MYSQL_DATABASE: testDatabase
    
  backend:
    build: ./Backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_PASSWORD: p@ssword
      SPRING_DATASOURCE_USER: testUser
      SPRING_DATASOURCE_NAME: testDatabase
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/testDatabase
    links:
      - database
  
  frontend:
    build:
      context: ./Frontend
    ports:
      - 4200:4200
    links:
      - backend

  

